[project]
name = "radiotomate"
version = "0.1.0"
description = "Broadcast automation for community radios"
authors = [
    {name="Martin Kirchgessner", email="martink@gresille.org"},
]
license = "AGPL-3.0-or-later"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Linux",
    "Development Status :: 3 - Alpha",
]

[project.urls]
"Source" = "https://git.sr.ht/~martink/radiotomate"

[tool.poetry.dependencies]
python = "^3.11"
click = "~8.2.0" # switch to ^8.3.1 once released, because of https://github.com/pallets/click/pull/3068
argon2-cffi = "^23.1.0"
quart = "^0.19.6"
sqlalchemy = {extras = ["aiosqlite"], version = "^2.0.35"}
quart-auth = "^0.10.1"
multipart = "^1.1.0"
mutagen = "^1.47.0"
ruamel-yaml = "^0.18.6"
httpx = "^0.28.1"
apscheduler = {version="4.0.0a6", allow-prereleases = true, extras=["sqlalchemy"]}
beets = "~2.5.1"
drop2beets = "^2.0.1"

[tool.poetry.group.dev.dependencies]
rich = "^13.5.3"
pytest-asyncio = "^0.25.0"
ruff = "^0.8.4"
pytest-playwright-asyncio = "^0.6.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
radiotomate = "radiotomate.commands.main:radiotomate_cli"

[tool.pytest.ini_options]
addopts = "--capture=no --failed-first"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

[tool.ruff.lint]
select = [
    # flake8-builtins
    "A",
    # flake8-commas
    "COM",
    # flake8-comprehensions
    "C4",
    #flake8-debugger
    "T10",
    # flake8-gettext
    "INT",
    # flake8-logging
    "LOG",
    # flake8-logging-format
    "G",
    # flake8-no-pep420
    "INP",
    # flake8-pie
    "PIE",
    # flake8-print
    "T20",
    # flake8-pyi
    "PYI",
    # flake8-pytest-style
    "PT",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # flake8-type-checking
    "TC",
    # flake8-use-pathlib
    "PTH",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pep8-naming
    "N",
    # Pylint
    "PL",
    # pyupgrade
    "UP",
    # isort
    "I",
    # Ruff-specific rules
    "RUF",
]

ignore = [
    #if-else-block-instead-of-if-exp
    "SIM108",

    # Magic value used in comparison - we use it extensively for HTTP codes
    "PLR2004",

    # missing-trailing-comma - ruff format takes care of this
    "COM812",
]
